{% set name = "phonenumbers" %}
{% set version = "8.8.9" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "d819299c3aa8f85f248295ab8559e202af429b4017301b122a0b4c387aed10d2" %}
{% set build = 0 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash }}

build:
  noarch: python
  number: {{ build }}
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - phonenumbers
    - phonenumbers.carrierdata
    - phonenumbers.data
    - phonenumbers.geodata
    - phonenumbers.shortdata
    - phonenumbers.tzdata

about:
  home: https://github.com/daviddrysdale/python-phonenumbers
  # license_file: No LICENSE in MANIFEST, local copy below
  license_file: '{{ RECIPE_DIR }}/LICENSE'
  license: Apache 2.0
  license_family: Apache
  summary: "Python version of Google's common library for parsing, formatting, storing and validating international phone numbers."
  dev_url: https://github.com/daviddrysdale/python-phonenumbers

extra:
  recipe-maintainers:
    - pmlandwehr
