{% set name = "phonenumbers" %}
{% set version = "9.0.18" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5537c61ba95b11b992c95e804da6e49193cc06b1224f632ade64631518a48ed1

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python

test:
  source_files:
    - tests
    - testwrapper.py
  imports:
    - phonenumbers
    - phonenumbers.carrierdata
    - phonenumbers.data
    - phonenumbers.geodata
    - phonenumbers.shortdata
    - phonenumbers.tzdata
  commands:
    - pip check
    - pytest -v tests/phonenumbertest.py
  requires:
    - pip
    - pytest

about:
  home: https://github.com/daviddrysdale/python-phonenumbers
  license_file: LICENSE
  license: Apache-2.0
  license_family: Apache
  summary: "Python version of Google's common library for parsing, formatting, storing and validating international phone numbers."
  description: "Python version of Google's common library for parsing, formatting, storing and validating international phone numbers."
  dev_url: https://github.com/daviddrysdale/python-phonenumbers
  doc_url: https://github.com/daviddrysdale/python-phonenumbers/blob/dev/README.md

extra:
  recipe-maintainers:
    - pmlandwehr
