{% set version = "7.5.1" %}

package:
  name: phonenumbers
  version: {{ version }}

source:
  fn: phonenumbers-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/p/phonenumbers/phonenumbers-{{ version }}.tar.gz
  sha256: df81c483779011aa6f53c73c619723e2840ebb35d1cab01c071833c552b38d61

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - phonenumbers
    - phonenumbers.carrierdata
    - phonenumbers.data
    - phonenumbers.geodata
    - phonenumbers.shortdata
    - phonenumbers.tzdata

about:
  home: https://github.com/daviddrysdale/python-phonenumbers
  license: Apache 2.0
  summary: "Python version of Google's common library for parsing, formatting, storing and validating international phone numbers."

extra:
  recipe-maintainers:
    - pmlandwehr
