{% set name = "phonenumbers" %}
{% set version = "8.12.44" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "26cfd0257d1704fe2f88caff2caabb70d16a877b1e65b6aae51f9fbbe10aa8ce" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel

  run:
    - python

test:
  imports:
    - phonenumbers
    - phonenumbers.carrierdata
    - phonenumbers.data
    - phonenumbers.geodata
    - phonenumbers.shortdata
    - phonenumbers.tzdata
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/daviddrysdale/python-phonenumbers
  # license_file: No LICENSE in MANIFEST, local copy below
  license_file: '{{ RECIPE_DIR }}/LICENSE'
  license: Apache-2.0
  license_family: Apache
  summary: "Python version of Google's common library for parsing, formatting, storing and validating international phone numbers."
  dev_url: https://github.com/daviddrysdale/python-phonenumbers
  doc_url: https://github.com/daviddrysdale/python-phonenumbers/blob/dev/README.md

extra:
  recipe-maintainers:
    - pmlandwehr
