{% set name = "phonenumbers" %}
{% set version = "8.13.49" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e608ccb61f0bd42e6db1d2c421f7c22186b88f494870bf40aa31d1a2718ab0ae

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel

  run:
    - python

test:
  imports:
    - phonenumbers
    - phonenumbers.carrierdata
    - phonenumbers.data
    - phonenumbers.geodata
    - phonenumbers.shortdata
    - phonenumbers.tzdata
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/daviddrysdale/python-phonenumbers
  license_file: LICENSE
  license: Apache-2.0
  license_family: Apache
  summary: "Python version of Google's common library for parsing, formatting, storing and validating international phone numbers."
  description: "Python version of Google's common library for parsing, formatting, storing and validating international phone numbers."
  dev_url: https://github.com/daviddrysdale/python-phonenumbers
  doc_url: https://github.com/daviddrysdale/python-phonenumbers/blob/dev/README.md

extra:
  recipe-maintainers:
    - pmlandwehr
