{% set version = "7.4.3" %}

package:
  name: phonenumbers
  version: {{ version }}

source:
  fn: phonenumbers-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/p/phonenumbers/phonenumbers-{{ version }}.tar.gz
  sha256: 0c15249588905f35e0efaa676c4d2b511a8dd5efa673765ac6b5469cb03f8d9a

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - phonenumbers
    - phonenumbers.carrierdata
    - phonenumbers.data
    - phonenumbers.geodata
    - phonenumbers.shortdata
    - phonenumbers.tzdata

about:
  home: https://github.com/daviddrysdale/python-phonenumbers
  license: Apache 2.0
  summary: "Python version of Google's common library for parsing, formatting, storing and validating international phone numbers."

extra:
  recipe-maintainers:
    - pmlandwehr
