travis:
  secure:
    BINSTAR_TOKEN: gV9LDK2FlFYSiWNxKtm2iTpLI0fZQ9ORcJpHL8j/cpx2yTeuWOSOfrjI7oqhFMAXy+edZAlA880TgWo/nU46r2C4LjoYa8DTHJ/C5h7Pn+Ck9s/iBPL2Dvo8LrMAucI9xr32kyAucn/HOxLYGzdRXcZG8rwe5xqzJBnlYHB8DQI5CYFXEaMJbwXYxeDr4oTF7807Gixz1WdD6wO65crS3g3mKtEF7E9ENVLmfzKshP0hkD6U2XEwLn6Or9wSWvumVmst/3KgZ6lqvbY0e+32GYoAqi23gtcvvUze3pWK7OncARCoSbwm24AX48JCsxZ4P4nbYlMHkb1L+LId/dJz0TnR1W2s+uWWX+BrqrWvAsWU1Cd1GgZ+VNiUKv7AYGiVEPLCrfBiC2fv0/TYMBqfKB2ipY/LaCWoVT1/r1LWwrKtJzd1Epg0mFeKJvm88XpbTz87d84hZUuSKX6xBK77wWDEv90MBR/i2q2g5FLnguvqpklZ+QXfk2FJ3HPK1mIn1bKIK4HnyApDkTqbLK473zvF6dUjiBUb+kCjaapl0dVNtJ1zGOUM8DKNTGYGhPEua6N3QSnedyL0ndEbB6K8ur36pIplk1O1JIohOMlzAZznmYPu4PX5FRYflj5a2i5PAj77VQQok2glzbMex8zE99oYmVdEbAbhT9PprgdHTCo=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
