travis:
  secure:
    BINSTAR_TOKEN: Xdl7KRkuLRiM4PytLmQ9NPaS6eW7CoxwBw+QxP4CP1wGCvAk7qkqWghJqzJ1RS2rC7fuar72RvkvEVM4GBxUJZihFOuVZ4PAzAyjw03XaVoEsK+beibvD3b630aT7M9fywsze1sUAc0QEbYsZAVJNnCz910nu0jJ1Jrv0l6bAfgGPqivnipORs0pP/ikx5U9LWOY0RDykTtgbxiK+GZjrOwleH9W6MqwsQ1lTDdS6+hojiMwEO34/fqyG4Mnk+ma0eFKDQEm+o0HBAIzdif2iWKSY2DjJpq3GIgTYfTo3f33A0mXGsvKgKWj/zASdo/aDHKZyr5JJv1XPIujNOTUK83SDCT1Xov0Ap61UL9pCpAP0Ohof21AITlCEBJttOF9FygPi2DPBtwyK0SFcN7uN9IyExO2JNCRnU86fmFBRfQJkXHrAKOOuwgs/hSs9UYHEdYFer6kTI7L41wuS95c5mD0JxpBPtan4c5i9rKgUgrCzuy3+dUv4R+IzZq8NdBtyFgXMHH5cgAFtxRBUJuhTuw6weHBT8krXX3v+Kqmb37o5hIhSaIapoMX85LYWEdWk70olLDvVbip/ZAa3bGcGVkoqs5Qp6W2HFmgxxxvsgsPoXheWEk7I2LaZpyU5XcMsLRopA2oudVMWcfIJYl+57qmUyNN8rIfCVtID+VaTyw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
